development:
  adapter: postgresql
  encoding: unicode
  database: myccg_development
  pool: 5
  username: myccg
  password: password1
  host: localhost
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  database: myccg_test
  pool: 5
  username: myccg
  password: password1
  host: localhost
  port: 5432
